global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: keeper
    static_configs:
      - targets: ['host.docker.internal:8084']

remote_write:
- url: {{ getenv "PROM_REMOTE_WRITE_HOST" }}
  basic_auth:
    username: {{ getenv "PROM_REMOTE_WRITE_USERNAME" }}
    password: {{ getenv "PROM_REMOTE_WRITE_PASSWORD" }}
  metadata_config:
    send: true
    send_interval: 10s
    max_samples_per_send: 500

