version: '3'

services:
  prometheus:
    build: .
    # Eventhough exposing ports could be useful for discoverablilty
    # Not exposing will make it easier to have two scrapers running
    # ports:
    #  - 9090:9090
    environment:
     - PROM_REMOTE_WRITE_HOST
     - PROM_REMOTE_WRITE_USERNAME
     - PROM_REMOTE_WRITE_PASSWORD
     - PROM_ENDPOINT_TO_SCRAPE
     - PROM_JOB_NAME
    extra_hosts:
    - "host.docker.internal:host-gateway"