version: '3'

services:
  prometheus:
    build: .
    ports:
     - 9090:9090
    environment:
     - PROM_ENDPOINT_TO_SCRAPE
     - PROM_JOB_NAME
     - PROM_HTTP_PASSWORD
    extra_hosts:
    - "host.docker.internal:host-gateway"